services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
  knmi_checker:
    build: ./report_checker
    container_name: knmi_checker
    restart: always
    secrets:
      - notification_token
      - notification_client_id
      - open_data_api_token
    environment:
      - REDIS_CHANNEL=knmi_alerts
    depends_on:
      - redis
  telegram_notifier:
    build: ./notifier
    container_name: telegram_notifier
    restart: always
    environment:
      - REDIS_CHANNEL=knmi_alerts
    secrets:
      - telegram_bot_token
    depends_on:
      - redis
    # telegram_bot:
    #   build: ./knmi_bot
    #   container_name: telegram_bot
    #   restart: always
    #   secrets:
    #     - telegram_bot_token

secrets:
  notification_token:
    environment: KNMI_NOTIFICATION_TOKEN
  notification_client_id:
    environment: KNMI_NOTIFICATION_CLIENT_ID
  open_data_api_token:
    environment: KNMI_OPEN_DATA_API_TOKEN
  telegram_bot_token:
    environment: TELEGRAM_BOT_TOKEN
