[tools]
hadolint = "latest"
prek = "latest"
python = "latest"
uv = "latest"

[env]
_.file = { path = ".env" , redact = true, required =  false}
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }

[tasks.setup]
description = "Create/update project venv from pyproject + lock"
run = [
	"uv sync --frozen",
	"prek install -f",
]

[tasks.check-ty]
description = "Type check in project env"
depends = ["setup"]
run = "uv run ty check"

[tasks.lint]
description = "Lint in project env"
depends = ["setup"]
run = "uv run ruff check"


[tasks.format]
description = "Run formatting"
run = [
	"uv run ruff check --fix",
	"uv run ruff format",
]

[tasks.check-format]
description = "Check formatting"
run = "uv run ruff format --check"

[tasks.full-ci-check]
description = "Run format, lint, and type checks"
depends = ["check-format", "lint", "check-ty", "audit", "git-hooks"]
run = "true"

[tasks.audit]
description = "Audit dependencies for known vulnerabilities"
depends = ["setup"]
run = "uv audit --preview-features audit"

[tasks.git-hooks]
description = "Run prek hooks on all files"
run = "prek run --all-files"

[tasks.up]
description = "Start services with Docker Compose"
run = "docker compose up --build"

[tasks.clean]
description = "Clean generated files"
run = [
	"find . -type d -name '__pycache__' -exec rm -r {} +",
	"find . -type d -name '*.egg-info' -exec rm -r {} +",
]

[settings]
python.uv_venv_auto = "create|source"
